### ISSUE TITLE
Inline function and statements?

### ISSUE THREAD

**Issue by Kriechi** [philipbl/python-persistent-queue#1]
Hi,

I was reading through the code - all quite nice and clean.
However I stumbled upon this pieces - any I'm curios about your design decision here: 

https://github.com/philipbl/python-persistent-queue/blob/294677f5ca795cb9446f9bb41bc1b4db14386663/persistent_queue/__init__.py#L234-L236 
https://github.com/philipbl/python-persistent-queue/blob/294677f5ca795cb9446f9bb41bc1b4db14386663/persistent_queue/__init__.py#L259-L264

Why are these separate functions, not just a block within the for-loops, since they do not return anything?

**Comment by philipbl** [comment]
I like how it looks. You can read through the main logic of the function without having to worry about the details of those functions. Also, it mirrors the `_peek` function. But I could go either way -- it's just how I felt the day that I wrote it.
