### ISSUE TITLE
Support timeout for blocking peek/pop

### ISSUE THREAD

**Issue by Kriechi** [philipbl/python-persistent-queue#2]
It would be very useful to support the `timeout` argument for `pushed_event.wait()` function of `threading.Event`.

**Comment by philipbl** [comment]
I haven't needed this functionality where I am using python-persistent-queue so I haven't bothered implementing it yet. If you are interested, I will implement it eventually or you can make a PR.

**Comment by Kriechi** [comment]
I'm currently trying to adopt my application to use `python-persistent-queue` instead of the stdlib `queue.Queue`. However, there a few few minor API-incompatibilities. It would be nice to bring the API closer to the stdlib version. That's the reason why I'm missing `timeout` at the moment.
