### ISSUE TITLE
Blocking peek/pop: possible 100% CPU scenario

### ISSUE THREAD

**Issue by Kriechi** [philipbl/python-persistent-queue#3]
I think the current implementation (1b84b39bfc1e65a08f455ce0c18d5728c0e17976) of the `blocking` feature to `peek` and `pop` might lead to 100% CPU usage, imagine this scenario:
  * Queue is empty
  * Thread 1 calls `pop` with `blocking=True`
    * so this thread blocks to wait for a new item
  * Thread 2 pushes in a new item
    * the `pushed_event` is set, and triggers a wakeup of Thread 1
  * Thread 1 pops the only available item
  * Thread 1 tries to pop again with `blocking=True`
    * but now `pushed_event` is already set
    * so we get a spin-loop [here](https://github.com/philipbl/python-persistent-queue/blob/294677f5ca795cb9446f9bb41bc1b4db14386663/persistent_queue/__init__.py#L208), which is not very efficient

Ideally we call `pushed_event.clear()` when we take out the last element from the queue.

I'm aware that this kind of only is feasible for a `pop(1)` operation, since there is probably no way of determining number of available items before unblocking... Any ideas?

I'd like to propose adding a `get` function, similar to `queue.Queue` which only returns a single item. In this case the above mentioned blocking behaviour should be straight forward to implement.

**edit:**
A semaphore might be a more suitable solution here...

**Comment by philipbl** [comment]
Wow, thanks for point that out! Clearing the event after waiting for it should solve this problem:

``` python
if blocking:
    while self.count() < items:
        self.pushed_event.wait()
        self.pushed_event.clear()
```

**Comment by Kriechi** [comment]
Sounds about right. 👍 
I didn't want to patch around in `python-persistent-queue`, so at the moment I wrapped a semaphore around it. But it would be really nice to see your proposed change getting merged (and soon released as new version)!

**Comment by philipbl** [comment]
I've updated Pypi to the latest version:

https://pypi.python.org/pypi/python_persistent_queue/1.2.1

**Comment by Kriechi** [comment]
Yeah! 👍 
Thanks for the really fast response! I will try it out ASAP! 🎉
